# Generated by Django 4.2.9 on 2024-04-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='opening_date',
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
