# Generated by Django 4.2.9 on 2024-04-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_branch_capacity_branch_manager_branch_opening_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='batches',
            field=models.ManyToManyField(to='app.batch'),
        ),
    ]
