# Generated by Django 4.2.9 on 2024-04-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(to='app.subject'),
        ),
    ]
