# Generated by Django 4.2.9 on 2024-04-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.ManyToManyField(to='app.branch'),
        ),
    ]
