# Generated by Django 4.2.9 on 2024-04-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_course_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='document',
            field=models.ImageField(default=1, upload_to='course_documents/'),
            preserve_default=False,
        ),
    ]
