# Generated by Django 4.2.9 on 2024-04-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_course_branch_course_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branch',
        ),
    ]
