# Generated by Django 4.2.9 on 2024-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_branch_email_branch_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='password', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='your@gmail.com', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
