# Generated by Django 4.2.9 on 2024-04-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_course_location_teacher_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
