# Generated by Django 4.2.9 on 2024-04-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
