# Generated by Django 4.2.9 on 2024-04-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_paymentrequest_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
