# Generated by Django 4.2.9 on 2024-04-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_paymentrequest_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
