# Generated by Django 4.2.9 on 2024-04-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_paymentrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
