# Generated by Django 4.2.9 on 2024-04-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_paymentrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
