# Generated by Django 4.2.9 on 2024-04-24 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_fees_course_fees_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmpassword',
        ),
    ]
