# Generated by Django 4.2.9 on 2024-04-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_user_confirmpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
