# Generated by Django 4.2.9 on 2024-04-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_user_unique_id_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batches',
            field=models.ManyToManyField(null=True, to='app.batch'),
        ),
    ]
