# Generated by Django 4.2.9 on 2024-04-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_student_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
