# Generated by Django 4.2.9 on 2024-04-25 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_paymentrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
