# Generated by Django 4.2.9 on 2024-04-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_fees_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batches',
            field=models.ManyToManyField(null=True, related_name='student', related_query_name='students', to='app.batch'),
        ),
    ]
