# Generated by Django 4.2.9 on 2024-04-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_student_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DateofAdmission',
            field=models.DateField(null=True, verbose_name=django.db.models.deletion.CASCADE),
        ),
    ]
