# Generated by Django 4.2.9 on 2024-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_student_dateofadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Studentid',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
