# Generated by Django 4.2.9 on 2024-04-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_student_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentsession',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
