# Generated by Django 4.2.9 on 2024-04-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_course_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='marks_obtained',
            new_name='practical_marks_obtained',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='max_marks',
            new_name='practical_max_marks',
        ),
        migrations.AddField(
            model_name='marks',
            name='theory_marks_obtained',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='theory_max_marks',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
