# Generated by Django 4.2.9 on 2024-04-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_rename_marks_obtained_marks_practical_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='practical_marks_obtained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='practical_max_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='theory_marks_obtained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='theory_max_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
