# Generated by Django 4.2.9 on 2024-04-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_marks_practical_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branchstaticid',
            field=models.CharField(default='RTCBR00', max_length=20),
            preserve_default=False,
        ),
    ]
