# Generated by Django 4.2.9 on 2024-04-29 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_branch_phone_number_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='day',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
