# Generated by Django 4.2.9 on 2024-04-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_attendance_day_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
