# Generated by Django 4.2.9 on 2024-04-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_attendance_branch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='branch_id',
            new_name='batch_id',
        ),
    ]
