# Generated by Django 4.2.9 on 2024-04-29 16:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(default=datetime.date.today)),
                ('signup_amount', models.DecimalField(decimal_places=2, default=300.0, max_digits=4)),
                ('marksheet_amount', models.DecimalField(decimal_places=2, default=800.0, max_digits=5)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.branch')),
            ],
        ),
    ]
