# Generated by Django 4.2.9 on 2024-04-29 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_wallet_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='marksheet_amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='signup_amount',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.branch'),
        ),
    ]
