# Generated by Django 4.2.9 on 2024-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_remove_wallet_marksheet_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
