# Generated by Django 4.2.9 on 2024-04-29 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_transaction_branchstaticid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
