# Generated by Django 4.2.9 on 2024-04-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='signup_request',
            field=models.IntegerField(default=300),
        ),
    ]
