# Generated by Django 4.2.9 on 2024-04-30 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_wallet_signup_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DateofAdmission',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
