# Generated by Django 4.2.9 on 2024-04-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_student_dateofadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Studentid',
            field=models.CharField(default='RTC100', max_length=20),
        ),
    ]
