# Generated by Django 4.2.9 on 2024-04-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_student_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.branch'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
