# Generated by Django 4.2.9 on 2024-04-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_paymentrequest_branch_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='course_id',
            new_name='course',
        ),
    ]
