# Generated by Django 4.2.9 on 2024-05-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_rename_branch_id_paymentrequest_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='father_name',
            new_name='mother_name',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='batches',
            field=models.ManyToManyField(null=True, related_name='students', related_query_name='students', to='app.batch'),
        ),
    ]
