# Generated by Django 4.2.9 on 2024-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='marksheet_amount',
            field=models.IntegerField(default=800.0),
        ),
    ]
