# Generated by Django 4.2.9 on 2024-05-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_student_father_name_student_guardian_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='branch',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
