# Generated by Django 4.2.9 on 2024-05-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_oldmarksheet_oldsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='oldmarksheet',
            name='course_category',
        ),
        migrations.AddField(
            model_name='oldsubject',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.oldmarksheet'),
        ),
        migrations.AlterField(
            model_name='oldmarksheet',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.oldcourse'),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.oldcourse'),
        ),
    ]
