# Generated by Django 4.2.9 on 2024-05-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_oldcourse_remove_oldmarksheet_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldcourse',
            name='duration',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='oldcourse',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
