# Generated by Django 4.2.9 on 2024-05-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_oldcourse_duration_oldcourse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldsubject',
            name='practical_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='practical_max_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='theory_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='theory_max_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='total_max_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='total_obtained_marks',
            field=models.IntegerField(null=True),
        ),
    ]
