# Generated by Django 4.2.9 on 2024-05-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_alter_oldsubject_practical_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldsubject',
            name='course',
        ),
        migrations.AddField(
            model_name='oldsubject',
            name='course',
            field=models.ManyToManyField(to='app.oldcourse'),
        ),
    ]
