# Generated by Django 4.2.9 on 2024-05-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_remove_oldsubject_course_oldsubject_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldmarksheet',
            name='enrollment_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
