# Generated by Django 4.2.9 on 2024-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_oldmarksheet_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldmarksheet',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='oldmarksheet',
            name='roll_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oldmarksheet',
            name='serial_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='signup_pictures/'),
        ),
    ]
