# Generated by Django 4.2.9 on 2024-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_oldmarksheet_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='branch_profile_pics/'),
        ),
    ]
