# Generated by Django 4.2.9 on 2024-05-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_branch_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
