# Generated by Django 4.2.9 on 2024-05-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_remove_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='teacher_profile_pictures/'),
        ),
    ]
