# Generated by Django 4.2.9 on 2024-05-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_teacher_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='practical_marks_obtained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_max_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='theory_marks_obtained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='theory_max_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
