# Generated by Django 4.2.9 on 2024-05-13 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_subject_practical_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
