# Generated by Django 4.2.9 on 2024-05-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_alter_fees_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldsubject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='oldsubject',
            name='total_max_marks',
        ),
        migrations.RemoveField(
            model_name='oldsubject',
            name='total_obtained_marks',
        ),
    ]
