# Generated by Django 4.2.9 on 2024-05-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_remove_oldsubject_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldmarksheet',
            name='practical_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oldmarksheet',
            name='practical_max_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oldmarksheet',
            name='theory_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oldmarksheet',
            name='theory_max_marks',
            field=models.IntegerField(null=True),
        ),
    ]
