# Generated by Django 4.2.9 on 2024-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_oldmarksheet_practical_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldmarksheet',
            name='subjectname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
