# Generated by Django 4.2.9 on 2024-05-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_oldmarksheet_subjectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldmarksheet',
            name='enrollment_no',
            field=models.CharField(max_length=100),
        ),
    ]
