# Generated by Django 4.2.9 on 2024-05-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_alter_oldmarksheet_enrollment_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldmarksheet',
            name='practical_marks',
        ),
        migrations.RemoveField(
            model_name='oldmarksheet',
            name='practical_max_marks',
        ),
        migrations.RemoveField(
            model_name='oldmarksheet',
            name='subjectname',
        ),
        migrations.RemoveField(
            model_name='oldmarksheet',
            name='theory_marks',
        ),
        migrations.RemoveField(
            model_name='oldmarksheet',
            name='theory_max_marks',
        ),
        migrations.AddField(
            model_name='oldsubject',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.oldmarksheet'),
        ),
        migrations.AddField(
            model_name='oldsubject',
            name='total_max_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oldsubject',
            name='total_obtained_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oldmarksheet',
            name='enrollment_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='practical_max_marks',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='theory_max_marks',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
