# Generated by Django 4.2.9 on 2024-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_remove_oldmarksheet_practical_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldsubject',
            name='practical_marks',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='practical_max_marks',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='subject_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='theory_marks',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='theory_max_marks',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='total_max_marks',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='total_obtained_marks',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
