# Generated by Django 4.2.9 on 2024-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_alter_oldsubject_practical_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldsubject',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
    ]
