# Generated by Django 4.2.9 on 2024-05-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_alter_oldmarksheet_branch_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldmarksheet',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
