# Generated by Django 4.2.9 on 2024-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_alter_oldmarksheet_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldmarksheet',
            name='branch_state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='oldmarksheet',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='practical_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='practical_max_marks',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='theory_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='theory_max_marks',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='total_max_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oldsubject',
            name='total_obtained_marks',
            field=models.IntegerField(null=True),
        ),
    ]
