# Generated by Django 4.2.9 on 2024-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_alter_oldmarksheet_branch_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldmarksheet',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
