# Generated by Django 5.0.6 on 2024-05-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_student_receipt_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=9)),
                ('course', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=10)),
                ('paper_name', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.PositiveIntegerField()),
                ('exam_centre', models.CharField(max_length=255)),
            ],
        ),
    ]
