# Generated by Django 5.0.6 on 2024-05-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_monthlyadmitcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyadmitcard',
            name='receipt_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
