# Generated by Django 5.0.6 on 2024-05-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0105_monthlyadmitcard_receipt_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyadmitcard',
            name='receipt_path',
        ),
        migrations.AddField(
            model_name='student',
            name='monthlyAdmitCard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
