# Generated by Django 5.0.6 on 2024-05-27 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_student_enrollment_number_student_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheetrequest',
            name='Subject',
        ),
        migrations.AddField(
            model_name='marksheetrequest',
            name='Course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
            preserve_default=False,
        ),
    ]
