# Generated by Django 5.0.6 on 2024-05-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_remove_marksheetrequest_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheetrequest',
            name='marks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marks'),
        ),
    ]
