# Generated by Django 5.0.6 on 2024-05-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_alter_marksheetrequest_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheetrequest',
            name='issuedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
