# Generated by Django 5.0.6 on 2024-05-28 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_rename_pdf_url_oldmarksheet_certificate_pdf_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyadmitcard',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.branch'),
        ),
        migrations.AddField(
            model_name='yearlyadmitcard',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.branch'),
        ),
    ]
