# Generated by Django 5.0.6 on 2024-05-28 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_monthlyadmitcard_branch_yearlyadmitcard_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyadmitcard',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
