# Generated by Django 5.0.6 on 2024-05-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_alter_monthlyadmitcard_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyadmitcard',
            name='total_hours',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='yearlyadmitcard',
            name='paper1_total_hours',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='yearlyadmitcard',
            name='paper2_total_hours',
            field=models.CharField(max_length=10),
        ),
    ]
