# Generated by Django 5.0.6 on 2024-06-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_alter_monthlyadmitcard_total_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheetrequest',
            name='marksheet_pdf_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
