# Generated by Django 5.0.6 on 2024-07-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_marksheetrequest_marksheet_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldsubject',
            name='course',
        ),
        migrations.AddField(
            model_name='oldsubject',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.oldcourse'),
            preserve_default=False,
        ),
    ]
