# Generated by Django 5.0.6 on 2024-07-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_remove_oldsubject_course_oldsubject_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('no_of_holidays', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
